"""Built-in custom-agent tool catalog definitions."""

from __future__ import annotations

from typing import Any


def agent_tool(
    id: str,
    label: str,
    description: str,
    category: str,
    tool_name: str,
    risk: str = "low",
    requires_mcp_server: str | None = None,
) -> dict[str, Any]:
    return {
        "id": id,
        "label": label,
        "description": description,
        "category": category,
        "tool_name": tool_name,
        "risk": risk,
        "requires_mcp_server": requires_mcp_server,
    }


AGENT_TOOL_CATALOG: list[dict[str, Any]] = [
    agent_tool("read_file", "Read files", "Read repository and generated artifact files.", "Workspace", "Read"),
    agent_tool("list_files", "List files", "Inspect directories and workspace structure.", "Workspace", "LS"),
    agent_tool("glob_files", "Find files", "Find files by pattern.", "Workspace", "Glob"),
    agent_tool("grep_files", "Search text", "Search file contents by pattern.", "Workspace", "Grep"),
    agent_tool("write_file", "Write files", "Create or overwrite files in the workspace.", "Workspace", "Write", "high"),
    agent_tool("edit_file", "Edit files", "Apply targeted edits to workspace files.", "Workspace", "Edit", "high"),
    agent_tool(
        "multi_edit_file",
        "Multi-edit files",
        "Apply multiple edits to workspace files in one operation.",
        "Workspace",
        "MultiEdit",
        "high",
    ),
    agent_tool("bash", "Shell command", "Run shell commands in the agent workspace.", "Workspace", "Bash", "destructive"),
    agent_tool(
        "browser_navigate",
        "Browser navigate",
        "Open web pages in an isolated Playwright browser.",
        "Browser",
        "mcp__playwright-test__browser_navigate",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_navigate_back",
        "Browser back",
        "Return to the previous page in browser history.",
        "Browser",
        "mcp__playwright-test__browser_navigate_back",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_close",
        "Browser close",
        "Close the active browser page.",
        "Browser",
        "mcp__playwright-test__browser_close",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_snapshot",
        "Browser snapshot",
        "Read the current page accessibility tree.",
        "Browser",
        "mcp__playwright-test__browser_snapshot",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_click",
        "Browser click",
        "Click page elements.",
        "Browser",
        "mcp__playwright-test__browser_click",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_type",
        "Browser type",
        "Type into page inputs.",
        "Browser",
        "mcp__playwright-test__browser_type",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_drag",
        "Browser drag",
        "Drag one page element onto another.",
        "Browser",
        "mcp__playwright-test__browser_drag",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_hover",
        "Browser hover",
        "Hover over page elements.",
        "Browser",
        "mcp__playwright-test__browser_hover",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_evaluate",
        "Browser JavaScript",
        "Evaluate JavaScript in the page context.",
        "Browser",
        "mcp__playwright-test__browser_evaluate",
        "high",
        "playwright-test",
    ),
    agent_tool(
        "browser_select",
        "Browser select",
        "Choose values in dropdowns.",
        "Browser",
        "mcp__playwright-test__browser_select_option",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_press_key",
        "Browser key press",
        "Press keyboard keys in the page.",
        "Browser",
        "mcp__playwright-test__browser_press_key",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_upload",
        "File upload",
        "Upload files into a page.",
        "Browser",
        "mcp__playwright-test__browser_file_upload",
        "high",
        "playwright-test",
    ),
    agent_tool(
        "browser_dialog",
        "Handle dialogs",
        "Accept or dismiss browser dialogs.",
        "Browser",
        "mcp__playwright-test__browser_handle_dialog",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_network",
        "Network requests",
        "Inspect browser network traffic.",
        "Diagnostics",
        "mcp__playwright-test__browser_network_requests",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_console",
        "Console messages",
        "Inspect browser console output.",
        "Diagnostics",
        "mcp__playwright-test__browser_console_messages",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_screenshot",
        "Screenshot",
        "Capture browser screenshots.",
        "Diagnostics",
        "mcp__playwright-test__browser_take_screenshot",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_wait",
        "Browser wait",
        "Wait for text, disappearance, or time.",
        "Diagnostics",
        "mcp__playwright-test__browser_wait_for",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_generate_locator",
        "Generate locator",
        "Generate a robust locator for a page element.",
        "Testing",
        "mcp__playwright-test__browser_generate_locator",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_verify_element",
        "Verify element visible",
        "Check that a target element is visible.",
        "Assertions",
        "mcp__playwright-test__browser_verify_element_visible",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_verify_list",
        "Verify list visible",
        "Check that a list of elements is visible.",
        "Assertions",
        "mcp__playwright-test__browser_verify_list_visible",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_verify_text",
        "Verify text visible",
        "Check that expected text is visible.",
        "Assertions",
        "mcp__playwright-test__browser_verify_text_visible",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_verify_value",
        "Verify value",
        "Check an element value.",
        "Assertions",
        "mcp__playwright-test__browser_verify_value",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_resume",
        "Resume browser",
        "Resume browser state for diagnostic workflows.",
        "Testing",
        "mcp__playwright-test__browser_resume",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "browser_start_tracing",
        "Start tracing",
        "Start browser tracing for diagnostics.",
        "Diagnostics",
        "mcp__playwright-test__browser_start_tracing",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "browser_stop_tracing",
        "Stop tracing",
        "Stop browser tracing and collect trace artifacts.",
        "Diagnostics",
        "mcp__playwright-test__browser_stop_tracing",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "test_list",
        "List tests",
        "List runnable Playwright tests.",
        "Testing",
        "mcp__playwright-test__test_list",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "test_run",
        "Run tests",
        "Run Playwright tests and collect failure output.",
        "Testing",
        "mcp__playwright-test__test_run",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "planner_setup_page",
        "Planner setup page",
        "Prepare a page for planner workflows.",
        "Pipeline",
        "mcp__playwright-test__planner_setup_page",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "planner_save_plan",
        "Planner save plan",
        "Save a generated test plan artifact.",
        "Pipeline",
        "mcp__playwright-test__planner_save_plan",
        "high",
        "playwright-test",
    ),
    agent_tool(
        "generator_setup_page",
        "Generator setup page",
        "Prepare a page for generator workflows.",
        "Pipeline",
        "mcp__playwright-test__generator_setup_page",
        "medium",
        "playwright-test",
    ),
    agent_tool(
        "generator_read_log",
        "Generator read log",
        "Read generator workflow logs.",
        "Pipeline",
        "mcp__playwright-test__generator_read_log",
        requires_mcp_server="playwright-test",
    ),
    agent_tool(
        "generator_write_test",
        "Generator write test",
        "Write generated Playwright test code.",
        "Pipeline",
        "mcp__playwright-test__generator_write_test",
        "high",
        "playwright-test",
    ),
]


AGENT_RISK_ORDER = {"low": 0, "medium": 1, "high": 2, "destructive": 3}
