"""Facade setup for legacy agent helpers exposed from main."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from . import (
    agent_compat_alias_support,
    agent_exploratory,
    agent_reports,
    agent_run_control,
    agent_run_launch,
)

RuntimeFactory = Callable[[], Any]

_AGENT_COMPAT_ALIAS_NAMES = (
    "_agent_tool",
    "AGENT_TOOL_CATALOG",
    "AGENT_RISK_ORDER",
    "_sync_agent_run_observability_runs_dir",
    "_collect_agent_run_artifacts",
    "_read_run_text_artifact",
    "_read_run_json_artifact",
    "_run_artifact_counts",
    "_jsonl_latest_url",
    "_latest_observed_url_for_run",
    "_recover_custom_agent_partial_result",
    "_agent_run_summary",
    "_exploratory_result_is_zero_evidence_failure",
    "_exploratory_result_is_terminal_failure",
    "_exploratory_result_has_usable_evidence",
    "_merge_agent_failure_into_result",
    "_recover_exploratory_partial_result",
    "_filter_agent_run_project",
    "_agent_report_project_filter",
    "_get_agent_report_run",
    "AGENT_PARTIAL_STATUS",
    "AGENT_TERMINAL_STATUSES",
    "AGENT_ACTIVE_STATUSES",
    "_coerce_progress_int",
    "_normalize_agent_run_progress",
    "_record_agent_run_event",
    "_start_agent_run_temporal_or_fail",
    "_agent_run_temporal_payload",
    "_signal_agent_run_temporal",
    "_cancel_agent_run_queue_task",
    "_wait_if_agent_run_paused",
    "_mark_agent_run_paused",
    "_mark_agent_run_cancelled",
    "_agent_run_health",
    "_serialize_agent_run",
    "_safe_json_dict",
    "_compact_agent_run_config",
    "_compact_agent_run_summary",
    "_encode_agent_run_cursor",
    "_decode_agent_run_cursor",
    "_agent_run_project_filters",
    "_agent_run_search_filter",
    "_agent_run_status_filter",
    "_agent_run_type_filter",
    "_agent_run_history_filters",
    "_agent_run_history_counts",
    "_serialize_agent_run_summary_row",
    "_live_agent_queue_progress",
    "_serialize_agent_run_live",
    "REPORT_ITEM_COLLECTIONS",
    "REPORT_ITEM_EDITABLE_FIELDS",
    "REPORT_ITEM_LIST_FIELDS",
    "REPORT_ITEM_PROTECTED_FIELDS",
    "_report_confidence",
    "_report_importance",
    "_report_requirement_confidence",
    "_report_requirement_acceptance_criteria",
    "_requirement_create_body_from_report_item",
    "_normalize_report_item_type",
    "_stored_custom_agent_report",
    "_normalize_report_patch_value",
    "_editable_report_item_patch",
    "_find_report_item",
    "_capture_custom_agent_report_memory",
    "_sync_agent_tool_catalog",
    "_serialize_agent_tool",
    "_serialize_agent_definition",
    "_get_agent_definition_or_404",
    "_ensure_agent_write_access",
    "_resolve_agent_tools",
    "_browser_auth_selection",
    "AgentBrowserAuthResolutionError",
    "_browser_auth_request_fields_set",
    "_without_spec_generation_auth",
    "_apply_report_spec_browser_auth_request",
    "_resolve_agent_browser_auth_storage_path",
    "_prepare_custom_agent_mcp_config",
    "_prepare_spec_generation_mcp_config",
    "_safe_inherited_auth_config",
    "_build_spec_generation_source_config",
    "_spec_generation_auth_metadata",
    "_resolve_playwright_chromium_executable",
    "_playwright_chromium_probe_script",
    "_probe_custom_agent_browser",
    "_probe_custom_agent_browser_with_slot",
    "_custom_agent_uses_browser_tools",
    "_custom_agent_browser_runs_via_queue",
    "_agent_run_has_browser_tools",
    "_ensure_custom_agent_browser_available",
    "_worker_managed_agent_browser_slot",
    "_short_tool_name",
    "_update_agent_run_progress",
    "_generic_agent_runtime_prompt",
    "KNOWN_AGENT_TYPE_TOOL_PROFILES",
    "_agent_tool_profile_for_run",
    "_resolve_known_agent_allowed_tools",
    "_resolve_agent_execution_test_data_context",
    "_agent_background_runner_dependencies",
    "execute_agent_background",
    "_agent_exploratory_dependencies",
    "_verify_exploration_run_project",
    "_build_single_flow_prompt",
    "_generate_fallback_spec",
    "_requires_authentication",
    "_detect_login_url",
    "_is_login_page",
    "_extract_domain_name",
    "_slugify",
    "_flow_spec_jobs",
    "MAX_FLOW_SPEC_JOBS",
    "_cleanup_flow_spec_jobs",
    "_run_flow_spec_generation",
)


def configure_agent_facade(runtime_factory: RuntimeFactory, namespace: dict[str, Any]) -> None:
    """Populate main-module compatibility exports for agent helpers."""
    runtime_factory()

    namespace.update(
        {
            "AgentRunRequest": agent_run_launch.AgentRunRequest,
            "ExploratoryRunRequest": agent_exploratory.ExploratoryRunRequest,
            "SpecSynthesisRequest": agent_exploratory.SpecSynthesisRequest,
            "FlowUpdateRequest": agent_exploratory.FlowUpdateRequest,
            "GenerateReportItemSpecRequest": agent_exploratory.GenerateReportItemSpecRequest,
            "ImportReportRequirementsRequest": agent_reports.ImportReportRequirementsRequest,
            "UpdateAgentReportItemRequest": agent_reports.UpdateAgentReportItemRequest,
            "UpdateAgentReportOverviewRequest": agent_reports.UpdateAgentReportOverviewRequest,
            "GenerateFlowTestRequest": agent_exploratory.GenerateFlowTestRequest,
            "run_agent": agent_run_launch.run_agent,
            "pause_agent_run": agent_run_control.pause_agent_run,
            "resume_agent_run": agent_run_control.resume_agent_run,
            "cancel_agent_run": agent_run_control.cancel_agent_run,
            "retry_agent_run": agent_run_control.retry_agent_run,
            "get_agent_run_report": agent_reports.get_agent_run_report,
            "update_agent_run_report_overview": agent_reports.update_agent_run_report_overview,
            "update_agent_run_report_item": agent_reports.update_agent_run_report_item,
            "search_agent_reports": agent_reports.search_agent_reports,
            "import_agent_report_requirements": agent_reports.import_agent_report_requirements,
            "run_exploratory_agent": agent_exploratory.run_exploratory_agent,
            "synthesize_specs": agent_exploratory.synthesize_specs,
            "get_exploration_specs": agent_exploratory.get_exploration_specs,
            "get_flow_details": agent_exploratory.get_flow_details,
            "update_flow": agent_exploratory.update_flow,
            "delete_flow": agent_exploratory.delete_flow,
            "analyze_prerequisites": agent_exploratory.analyze_prerequisites,
            "generate_flow_spec": agent_exploratory.generate_flow_spec,
            "get_flow_spec_job_status": agent_exploratory.get_flow_spec_job_status,
            "generate_report_item_spec": agent_exploratory.generate_report_item_spec,
            "generate_flow_test": agent_exploratory.generate_flow_test,
        }
    )
    namespace.update({name: getattr(agent_compat_alias_support, name) for name in _AGENT_COMPAT_ALIAS_NAMES})

    agent_exploratory.configure_dependencies_provider(namespace["_agent_exploratory_dependencies"])
