"""Route module compatibility exports for the legacy main module facade."""

from __future__ import annotations

from typing import Any

from . import (
    agent_coding_patch,
    agent_definitions,
    agent_exploratory,
    agent_queue_ops,
    agent_reports,
    agent_run_control,
    agent_run_launch,
    agent_run_observability,
    agent_sessions,
    analytics,
    api_testing,
    auth,
    autonomous,
    autopilot,
    backup_control,
    browser_auth_sessions,
    chat,
    ci_control,
    dashboard,
    database_testing,
    exploration,
    github_ci,
    gitlab_ci,
    health,
    jira,
    llm_testing,
    load_testing,
    memory,
    prd,
    projects,
    recordings,
    regression,
    requirements,
    rtm,
    run_files,
    runs,
    runtime_ops,
    scheduling,
    security_testing,
    settings,
    spec_files,
    specs,
    test_data,
    testrail,
    testrail_files,
    users,
    workflows,
)


def configure_main_route_module_facade(namespace: dict[str, Any]) -> None:
    """Populate main-module compatibility exports for route modules."""
    namespace.update(
        {
            "agent_coding_patch": agent_coding_patch,
            "agent_definitions": agent_definitions,
            "agent_exploratory": agent_exploratory,
            "agent_queue_ops": agent_queue_ops,
            "agent_reports": agent_reports,
            "agent_run_control": agent_run_control,
            "agent_run_launch": agent_run_launch,
            "agent_run_observability": agent_run_observability,
            "agent_sessions": agent_sessions,
            "analytics": analytics,
            "api_testing": api_testing,
            "auth": auth,
            "autonomous": autonomous,
            "autopilot": autopilot,
            "backup_control": backup_control,
            "browser_auth_sessions": browser_auth_sessions,
            "chat": chat,
            "ci_control": ci_control,
            "dashboard": dashboard,
            "database_testing": database_testing,
            "exploration": exploration,
            "github_ci": github_ci,
            "gitlab_ci": gitlab_ci,
            "health": health,
            "jira": jira,
            "llm_testing": llm_testing,
            "load_testing": load_testing,
            "memory": memory,
            "prd": prd,
            "projects": projects,
            "recordings": recordings,
            "regression": regression,
            "requirements": requirements,
            "rtm": rtm,
            "run_files": run_files,
            "runs": runs,
            "runtime_ops": runtime_ops,
            "scheduling": scheduling,
            "security_testing": security_testing,
            "settings": settings,
            "spec_files": spec_files,
            "specs": specs,
            "test_data": test_data,
            "testrail": testrail,
            "testrail_files": testrail_files,
            "users": users,
            "workflows": workflows,
        }
    )
